blog/urls.py
from django.conf.urls import url,include
from django.conf.urls.static import static
from django.contrib import admin
from django.conf import settings

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('news.urls')),
]
if settings.DEBUG:
    urlpatterns+=static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns+=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

news/urls.py
from django.conf.urls import url
from . import views
app_name = 'news'
urlpatterns = [
        url(r'^$',views.home, name='home'),
        url(r'^news_list', views.news_list, name='news_list'),
        url(r'^news/(?P<id>\d+)/$', views.news_detail, name="news_detail"),
        url(r'^create_news', views.create_news, name='create_news'),
        url(r'^delete/(?P<id>\d+)/$', views.delete_news, name='delete'),
        url(r'^update/(?P<id>\d+)/$', views.update_news, name='update'),

]

news/models.py
from django.db import models

# Create your models here.
class Cat(models.Model):
    ctgry = models.CharField(max_length=200)

    def __str__(self):
        return self.ctgry

class News(models.Model):
    nc = models.ForeignKey(Cat, null=True,blank=True)
    title = models.CharField(max_length=500)
    image = models.ImageField(blank=True,null=True)
    content = models.TextField()
    updated = models.DateTimeField(auto_now=True, auto_now_add=False)
    timestamp = models.DateTimeField(auto_now=False, auto_now_add=True)

    def __str__(self):
        return self.title

news/forms.py
from django import forms
from .models import News,Cat

class CreateNews(forms.ModelForm):

    class Meta:
        model = News
        fields = (
            'nc',
            'title',
            'image',
            'content',
        )

news/views.py
from django.shortcuts import render,get_object_or_404,redirect
from django.http import HttpResponse
from django.contrib import messages
from django.core.paginator import Paginator,PageNotAnInteger,EmptyPage
from .models import News,Cat
from django.db.models import Q
from .forms import CreateNews

def home(request):
    context={}
    template = 'home.html'
    return render(request,template,context)

def create_news(request):
    form = CreateNews(request.POST or None,request.FILES or None)
    if form.is_valid():
        instance = form.save(commit=False)
        instance.save()
        messages.success(request,"Post successfully created")
        return redirect('news:news_list')
    context = {'form':form}
    template = 'create_news.html'
    return render(request,template,context)


def news_detail(request,id=None):
    n = get_object_or_404(News, id = id)
    context = {'news':n}
    template = 'news_detail.html'
    return render(request,template,context)

# list of all news
def news_list(request):
    n = News.objects.all().order_by("-timestamp")
    ctb = Cat.objects.all()
    page = request.GET.get('page')
    paginator = Paginator(n,12)
    try:
        users = paginator.page(page)
    except PageNotAnInteger:
        users = paginator.page(1)
    except EmptyPage:
        users = paginator.page(paginator.num_pages)
    query = request.GET.get('q')
    if query:
        n = n.filter(
            Q(title__icontains = query)|
            Q(content__icontains = query)
              )
    context = {'users':users, 'ct':ctb}
    template = 'news_list.html'
    return render(request,template,context)


def update_news(request,id=None):
    d = get_object_or_404(News, id=id)
    form = CreateNews(request.POST or None,request.FILES or None, instance=d)
    if form.is_valid():
        d = form.save(commit=False)
        d.save()
        messages.success(request, "Post successfully updated.")
        return redirect('news:news_list')
    template = 'create_news.html'
    context = {'d':d,
               'form':form}
    return render(request,template,context)



def delete_news(request,id=None):
    n = get_object_or_404(News, id=id)
    n.delete()
    messages.success(request, "Post successfully deleted")
    return redirect('news:news_list')

news/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% load static %}

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    {% block head %}<title>Home|Blog</title>{% endblock %}
    <style>

    body{
          background-color: #e8e4e4;

    }
</style>
</head>
<body>
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="{% url 'news:home' %}">News Blog</a>
    </div>
    <div class="collapse navbar-collapse" id="myNavbar">
      <ul class="nav navbar-nav">
        <li class="active"><a href="{% url 'news:home' %}">Home</a></li>
       <li><a href="{% url 'news:create_news' %}">Create News</a></li>
        <li><a href="{% url 'news:news_list' %}">Blog</a></li>

      </ul>

    </div>
  </div>
</nav>


{% block content %}


{% endblock %}
<footer style="background:black; color:white;">
    <h5 class="text-center">Designed & Developed By: Saloni Sandhu</h5>
</footer>

<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js" integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js" integrity="sha384-h0AbiXch4ZDo7tp9hKZ4TsHbi047NrKGLO3SEJAg45jXxnGIfYzk4Si90RDIqNm1" crossorigin="anonymous"></script>
</body>

</html>

news/templates/create_news.html
{% extends 'base.html' %}
{% block head %}
<title>Blog|Homepage</title>
{% endblock %}
{% block content %}
<div class="container">
    <h3>Create New</h3>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-success">Create News</button>
    </form>

</div>
{% endblock %}

news/templates/home.html
{% extends 'base.html' %}
{% block head %}
<title>Blog|Homepage</title>
{% endblock %}
{% block content %}
<div class="container">
    <h3 class="text-center">Welcome to our bloging site:</h3>
    <h2 class="text-center text-danger">Faeture of this site</h2>
    <p class="text-center text-alert">You can read post</p>
    <p class="text-center text-danger">You can create post</p>
    <p class="text-center">You can edit post</p>
    <p class="text-center text-warning">You can delete post</p>
    <p class="text-center text-success">You can upload image with post</p>

</div>
{% endblock %}

news/templates/news_detail.html
{% extends 'base.html' %}
{% block head %}
<title>{{news.title}}</title>
{% endblock %}
{% block content %}
<div class="container">
    <div class="col-md-7">
    <a href="{% url 'news:news_list' %}">Go Back</a>
    <h3>{{news.title}}</h3><hr>
    <img src="{{news.image.url}}" class="img-responsive"/>
    <p>{{news.content}}</p>
    </div>
</div>
{% endblock %}

news/templates/news_list.html
{% extends 'base.html' %}
{%block head%}
<title>News Detail|Blog</title>
{%endblock%}

{% block content %}
<div class="container">
    {% if messages %}

    {% for message in messages %}
    <script>
      alert('{{ message }}')
    </script>
    {% endfor %}

{% endif %}
<form method="get">

</form>
   <h2 class="text-center">Latest News</h2><hr>
<div class="col-md-12">
    <form>
        <input type="text" placeholder="Search News.." name="q" value="{{request.GET.q}}">
        <input type="submit" value="Search" class="btn">
    </form>

       {% for user in users %}

   <div class="panel panel-default col-md-3" style="background:whitesmoke; border: 5px solid #e8e4e4; border-radius:15px;">
           <h4>{{user.title}}</h4>
       {% if user.image %}
       <img src="{{user.image.url}}"  height="150;" width="170"/>
       {% endif %}
       <p>{{user.content|truncatechars:30}}</p>
      <a href="{% url 'news:news_detail' user.id %}">
          <button type="button" class="btn btn-primary btn-xs pull-right">Read More...</button>
      </a>
       <a href="{% url 'news:delete' user.id %}">
       <span class="glyphicon glyphicon-trash"></span>
           </a>
       <a href="{% url 'news:update' user.id %}">
       <span class="glyphicon glyphicon-pencil"></span>
           </a>
   </div>

   {% endfor %}

</div>
    <div class="clearfix"></div>

     <div class="col-md-12 text-center">
         {% if users.has_other_pages %}
  <ul class="pagination">
    {% if users.has_previous %}
      <li><a href="?page={{ users.previous_page_number }}">&laquo;</a></li>
    {% else %}
      <li class="disabled"><span>&laquo;</span></li>
    {% endif %}
    {% for i in users.paginator.page_range %}
      {% if users.number == i %}
        <li class="active"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
      {% else %}
        <li><a href="?page={{ i }}">{{ i }}</a></li>
      {% endif %}
    {% endfor %}
    {% if users.has_next %}
      <li><a href="?page={{ users.next_page_number }}">&raquo;</a></li>
    {% else %}
      <li class="disabled"><span>&raquo;</span></li>
    {% endif %}
  </ul>
{% endif %}
     </div>
    <div class="clearfix"></div>
{%endblock%}